public class arithmeticexception
{
	public static void main(String args[])
	{
		int a=0;
		int b=5;
		System.out.println("hello");
		int c=b/a;
		System.out.println("end of the program");
		}
	}
	//another program solve the exception using try catch method